import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Muth Farm Flowers",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className="bg-base-100" lang="en">
			<body >{children}</body>
		</html>
	);
}
