import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Muth Farm Flowers",
	description: "Generated by create next app",
};

export const viewport: Viewport = {
	initialScale: 1,
	width: "device-width",
	maximumScale: 1
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className="bg-base-100 overflow-x-hidden" lang="en">
			<body >{children}</body>
		</html>
	);
}
